// 1. Take a name and make it greet like "Hello, JOHN!"
// 2. Get the length of the string "JavaScript"
// 3. Check if "apple" exists in "I like apple pie"
// 4. Find where the word "code" starts in "Learn to code every day"
// 5. Replace "bad" with "good" in "That is a bad idea"
// 6. Remove extra spaces from "   JavaScript   "
// 7. Reverse the string "hello"
// 8. Convert "hello world" → "Hello World"
// 9. Convert "john.doe@gmail.com" → "j***@gmail.com"
// 10. Count how many times 'a' appears in "banana"
// 11. From "https://www.google.com" get "google.com"
// 12. Check if "JavaScript" starts with "Java" and ends with "Script"
// 13. Count how many times each word appears in "I love JavaScript because JavaScript is awesome"
// 14. Return the longest word in a sentence
// 15. Convert "Learn JavaScript in 2025!" → "learn-javascript-in-2025"